name: Docker Image CI

on:
  workflow_dispatch: { }

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username:  ${{ secrets.DOCKER_USER }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -t kiliokuara/vivo50:${{ github.sha }} -t kiliokuara/vivo50:latest
    - name: Push docker image
      run: docker push kiliokuara/vivo50:${{ github.sha }}
    - name: push latest
      run: docker push kiliokuara/vivo50:latest
